/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ReportId = IDL.Nat;
export const ReportStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'reported' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Urgency = IDL.Variant({
  'urgent' : IDL.Null,
  'standard' : IDL.Null,
});
export const Time = IDL.Int;
export const Category = IDL.Variant({
  'other' : IDL.Null,
  'graffiti' : IDL.Null,
  'garbage' : IDL.Null,
  'waterIssue' : IDL.Null,
  'pothole' : IDL.Null,
  'streetlight' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Report = IDL.Record({
  'id' : ReportId,
  'status' : ReportStatus,
  'title' : IDL.Text,
  'classificationLabel' : IDL.Text,
  'urgency' : Urgency,
  'createdAt' : Time,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'category' : Category,
  'image' : ExternalBlob,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Stats = IDL.Record({
  'resolvedReports' : IDL.Nat,
  'totalReports' : IDL.Nat,
  'urgentReports' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getRecentReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitReport' : IDL.Func([Report], [ReportId], []),
  'updateReportStatus' : IDL.Func([ReportId, ReportStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ReportId = IDL.Nat;
  const ReportStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'reported' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Urgency = IDL.Variant({ 'urgent' : IDL.Null, 'standard' : IDL.Null });
  const Time = IDL.Int;
  const Category = IDL.Variant({
    'other' : IDL.Null,
    'graffiti' : IDL.Null,
    'garbage' : IDL.Null,
    'waterIssue' : IDL.Null,
    'pothole' : IDL.Null,
    'streetlight' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Report = IDL.Record({
    'id' : ReportId,
    'status' : ReportStatus,
    'title' : IDL.Text,
    'classificationLabel' : IDL.Text,
    'urgency' : Urgency,
    'createdAt' : Time,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'category' : Category,
    'image' : ExternalBlob,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Stats = IDL.Record({
    'resolvedReports' : IDL.Nat,
    'totalReports' : IDL.Nat,
    'urgentReports' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getRecentReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitReport' : IDL.Func([Report], [ReportId], []),
    'updateReportStatus' : IDL.Func([ReportId, ReportStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };